// 9.22React高级/react-toutiao-my/src/components/items/multiple-pic/index.js
/**
 * @file multiple-pic component file
 * @author caoyaqin
 */

import React, {Component} from 'react';
import { itemFy } from '../decorators';
import style from './style.css';

@itemFy(true)
export default class MultiplePic extends Component {

    static classes = 'multiple-pic';

    render() {
        const { title, imageList } = this.props.data;
        return (
            <React.Fragment>
                <div className="title">{title}</div>
                <div className="image-list">
                    {
                        imageList.map((image, index) => (
                            <img key={index} src={image} />
                        ))
                    }
                </div>
            </React.Fragment>
        )
    }
}

// 8.30 Vue项目实战/vue-toutiao/src/components/items/multiple-pic.vue
<template>
  <div class="item multiple-image" on:click="aa">
    <h3 class="line3">{{title}}</h3>
    <div class="image-list">
      <img v-for="(imgPath, index) in imageList" :key="index" :src="imgPath" />
    </div>
  </div>
</template>

<script>
export default {

  props: ["title", "imageList"],

  data() {
    return {};
  }
  
};
</script>

<style scoped>
@import './index.css';
.multiple-image .image-list img {
    width: 33%;
}
</style>
